README.md

First version imported from collaborative pad.
* Everything could be rewritten without pity;
* Synchronization strategy is definitely naive so far (our use cases are too);
Please review:
Example of code that implemented another strategy to sync records with *Cliquet*:
* https://github.com/mozilla-services/readinglist/wiki/Client-phases
* https://hg.mozilla.org/releases/mozilla-aurora/file/18286de4be87/browser/components/readinglist/Sync.jsm
Synchronization using ETags:
* https://unhosted.org/practice/28/Synchronizing-browser-storage-with-server-storage.html

Draft dreamcode in README

---

README.md
package.json
src/collection.js
src/index.js
src/utils.js
test/index_test.js

r=? @leplatrem (code style, quality of implementation, docs review, any missing bits?)

First implementation of local CRUD operations.

---

.gitignore
README.md
package.json

[![Coverage Status](https://coveralls.io/repos/mozilla-services/cliquetis/badge.svg)](https://coveralls.io/r/mozilla-services/cliquetis)
Whenever I manage the turn the pill above green, it's probably good to merge.
Edit: it's likely to turn green once the patch lands into master.

Added support for code coverage & coveralls service.

---

src/collection.js
test/collection_test.js

refs #23 - r=? @ametaireau @leplatrem @natim

Fixes #23 - Don't bump local collection last_modified on conflicts.

---

src/collection.js
test/collection_test.js

Refs #25. I took the bare minimum approach here, though seems to serve the purpose.
Docs will be updated along #21.
r=? @leplatrem @ametaireau @Natim

Fixes #25 - Conflict resolution helper.

---

demo/demo.js
demo/index.html
docs/tutorial.md

Better docs, including tutorial

---

README.md

Don't mention cliquet in the readme.

---

.travis.yml
package.json
test/integration_test.js
test/scripts/kinto.ini
test/scripts/setup-kinto.sh

Just for fun, let's see how travis handles this.

Kinto setup script.

---

src/api.js
src/collection.js
test/api_test.js
test/collection_test.js
test/integration_test.js

This patch adds integration tests by setting up a local kinto server instance and run a test suite against it.
r=? @ametaireau @Natim @leplatrem

Added full integration test suite.

---

src/collection.js
src/utils.js
test/collection_test.js
test/utils_test.js

Closes #6 - Local collection data ordering & filtering.

---

src/api.js
test/api_test.js
test/scripts/setup-kinto.sh

I didn't think of this during the review...
@n1k0 r?

Add safety check if batch limit setting is falsy (fixes #64)

---

src/http.js
test/http_test.js

Fixes #69 - Handle deprecation header.

---

test/integration_test.js

Fixes #85 - Added integration test for deprecation headers.

---

docs/limitations.md
mkdocs.yml

Documented current known limitations.

---

src/collection.js
test/adapters/base_test.js
test/collection_test.js

r=? @ametaireau @leplatrem @Natim

Fixes #96 - Sync flow should stop when pushing changes fails.

---

README.md

Update after Kinto organization move.

---

src/collection.js
test/collection_test.js

Skip last pull if nothing to push

---

docs/installation.md

Fixes #103 - Updated links to public static assets.

---

docs/api.md

refs #120 - r=? @michielbdejong

Fixes #120 - Documented bucket option.

---

LICENCE
package.json

Change the license

---

src/collection.js
test/collection_test.js
test/integration_test.js

refs #158 - r=? @michielbdejong

Fixes #158 - Collection#create Id requirements validation.

---

test/integration_test.js

refs #185:
So we're better notified when oddities happen. r=? @michielbdejong

Fixes #185: detailed server error logging in case start fails.

---

CHANGELOG.md
package.json

Changelog:
- Fixed broken npm package.

1.0.0-rc.5

---

.gitignore
esdoc.json
package.json
src/adapters/IDB.js
src/adapters/LocalStorage.js
src/adapters/base.js
src/api.js
src/collection.js
src/errors.js
src/http.js
src/index.js
src/utils.js
test/adapters/IDB_test.js
test/adapters/localStorage_test.js
test/api_test.js
test/collection_test.js
test/http_test.js
test/index_test.js
test/utils_test.js

Reviewing instructions:
- checkout this branch
- `npm install`
- `esdoc -c esdoc.json`
- `open esdoc/index.html`
Once this is merged, we'll host the generated esdocs on https://doc.esdoc.org/.

Adds esdoc support.

---

.travis.yml

https://github.com/Kinto/kinto/releases/tag/1.5.1

Update to Kinto 1.5.1

---

docs/api.md
docs/extending.md
docs/hacking.md
docs/index.md
docs/tutorial.md

Mostly linking to appropriate sections of the detailed API docs.

Documentation improvements.

---

docs/index.md

Fix snippet doc index (create instead of add)

---

esdoc.json
package.json

Ref https://github.com/Kinto/kinto.js/pull/192#issuecomment-147077006

Fix import path in esdoc

---

src/KintoBase.js
src/api.js
src/collection.js
src/http.js

Fixes #215: Added internal links to esdoc.

---

docs/api.md
src/collection.js
test/api_test.js
test/collection_test.js

refs #176; r=? @michielbdejong

Fixes #176: Consistent sync result error reporting.

---

src/collection.js
test/collection_test.js
test/integration_test.js

refs #114; r=? @michielbdejong

Fixes #114: Drop collection metas on #clear().

---

.travis.yml
src/api.js
test/integration_test.js

Update to Kinto 1.6.2

---

docs/api.md

Refs #99. r=? @leplatrem @Natim

Fixes #99: Added docs for authorization.

---

.travis.yml

Updated travis configuration to install Kinto 1.7.0.

---

demo/demo.js

Fixes #231: Updated demo to handle flushed server.

---

docs/releasing.md
mkdocs.yml
package.json

Added docs for packaging and releasing Kinto.js.

---

.travis.yml

Update to Kinto 1.9.0

---

src/http.js
test/http_test.js

This is @n1k0's commit from #264 with my adaptation from #271 squashed into it.

Fixes #263: Handle network request timeouts. r=@leplatrem

---

src/api.js
src/collection.js
test/api_test.js
test/collection_test.js

Delete records locally when already deleted remotely (fixes #284)

---

docs/installation.md
package.json

The build weights 59K compared to 790K for unminified with polyfills
I could not come out without a good name, and ended up with «`noshim`».
What do you think ?

Add dist with minimalist version, without polyfills

---

CHANGELOG.md
demo/index.html
docs/installation.md
docs/tutorial.md
package.json

http://kintojs.readthedocs.org/en/latest/releasing/

Prepare 1.1.2

---

CHANGELOG.md
package.json

[Full Changelog](https://github.com/Kinto/kinto.js/compare/v1.1.2...v1.2.0)
**Implemented enhancements:**
- Allowing defining the remote endpoint in `#sync()`. [\#257](https://github.com/Kinto/kinto.js/issues/257)
- Lightweight dist files for modern browsers  [\#249](https://github.com/Kinto/kinto.js/issues/249)
**Fixed bugs:**
- Broken links in the doc [\#293](https://github.com/Kinto/kinto.js/issues/293)
- Fix JSM compatibility for Firefox adapter [\#274](https://github.com/Kinto/kinto.js/pull/274) ([leplatrem](https://github.com/leplatrem))
- Fix parsing of ES7 code in esdoc [\#294](https://github.com/Kinto/kinto.js/pull/294) ([leplatrem](https://github.com/leplatrem))

Prepare v1.2.0.

---

docs/api.md
src/collection.js
test/collection_test.js

Fixes #305: better err message when trying to recreate a virtually deleted record

---

demo/index.html
docs/hacking.md
docs/installation.md
docs/releasing.md
package.json

https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/
We can use this for Kinto.js releases !!

Subresource Integrity

---

docs/api.md
src/adapters/IDB.js
src/collection.js
src/utils.js
test/adapters/IDB_test.js
test/collection_test.js
test/utils_test.js

Add support for enum filters with indexed fields in DB adapter list()

---

package.json

We forgot to do it in https://github.com/Kinto/kinto.js/pull/321

Remove useless dependency for "for .. of" transpilation

---

docs/api.md

Just noticed a typo going through the docs.

colllection ~> collection

---

src/collection.js
test/collection_test.js
test/integration_test.js

Fix remote deletion

---

package.json
test/adapters/IDB_test.js
test/collection_test.js

Full code coverage.

---

fx-src/FirefoxStorage.js

fix failure in loadDump with no lastModified value

---

.travis.yml
test/kinto.ini

Add Kinto master as a TravisCI target (fixes #334)

---

package.json

See https://github.com/Kinto/kinto-admin/pull/12 and https://github.com/mozilla-services/react-jsonschema-form/pull/56

Add an 'engines' section for npm and node versions to package.json

---

package.json

Bump kinto client to 0.5.0

---

package.json

.gitignore and npm command updated

---

docs/extending.md
src/collection.js
test/collection_test.js

Remove one level of object in hooks payloads (fixes #357)

---

CHANGELOG.md
package.json

r=? @leplatrem 
Note: I have no idea why the changelog has been generated with so many changes. This thing is getting out of control and should be dropped at some point, so we only handle changelog for releases on github.

Bump v1.2.1.

---

docs/contributing.md
docs/installation.md
docs/releasing.md
docs/tutorial.md
package.json
test/index_test.js

* The `Kinto.adapters.LocalStorage` adapter was removed.
* The `BaseAdapter` interface for custom adapters has been updated.
* The HTTP Error messages format has been slightly updated. 
Since support for transactions has been introduced in this release, and as `localStorage` doesn't support any kind of transactions natively, we've decided to drop support for it in Kinto.js. Please swith to using IndexedDB (which is the default adapter), or create your own if you target another persistence implementation.
Since adapters now support transactions, the `BaseAdapter` interface now expect an `execute()` method to be implemented for custom adapters. The [Extending section](http://kintojs.readthedocs.org/en/latest/extending/#supporting-transactions) has been updated accordingly.
The string …

Bump v2.0.0

---

fx-src/FirefoxStorage.js

Use const for sqlite path in Gecko adapter

---

.travis.yml

Upgrade server version in tests

---

src/collection.js
test/collection_test.js

Refs #399, pair=@leplatrem
Note that this doesn't address #16.

Fixes #399: Fixed incoming error object formatting.

---

fx-src/jsm_prefix.js
package.json
src/collection.js
src/utils.js
test/utils_test.js

Simple object comparison function (ref #402)

---

README.md
docs/api.md
docs/contributing.md
docs/index.md
docs/limitations.md
docs/releasing.md
docs/tutorial.md

Update Readthedocs links.

---

package.json

Changelog:
- Merged #417: Ensure manually resolved conflicts are always published to the server.

Bump v2.0.4.

---

src/collection.js
test/collection_test.js
test/integration_test.js

Do not publish resolved conflicts with remote version (fixes #419)

---

docs/api.md
docs/upgrading.md
package.json
src/collection.js
test/collection_test.js

Revamp of #389 
Fixes #335 
Take any feedback on approach/wording

Previous version of record in sync result (fixes #335)

---

docs/api.md
docs/installation.md
package.json
test/integration_test.js

Prepare release 3.0

---

README.md
docs/api.md
docs/limitations.md
src/KintoBase.js

Fixes #67 
Fixes #348 
@glasserc r?

Raw http calls

---

fx-src/index.js
src/collection.js
test/collection_test.js

Use IndexedDB by default in collection (fixes #345)

---

src/collection.js
test/collection_test.js

Raise with nice error if incoming-changes hook returns bad value (fixes #425)

---

src/collection.js

Minor consistency rewrite of safe option in push changes

---

src/collection.js
test/collection_test.js

It conflicts with #460 but rebase/merge is trivial.
@glasserc r?

Reject when deleting already deleted record (fixes #458)

---

src/collection.js
test/collection_test.js

Another fix for my webextensions work. This facilitates generating notifications for deleted records.

Return deleted records

---

.babelrc
docs/api.md
docs/extending.md
fx-src/index.js
package.json
src/KintoBase.js
src/adapters/IDB.js
src/collection.js
src/index.js
test/adapters/IDB_test.js
test/collection_test.js
test/integration_test.js
test/test_utils.js

apologies for making new PR, but unfortunately I screwed up that PR

Leverage the babel rest-object spread plugin #304

---

fx-src/FirefoxStorage.js
src/adapters/IDB.js
src/collection.js
test/adapters/IDB_test.js
test/collection_test.js

Removing reentrancy (fixes #446)

---

docs/api.md
src/collection.js
test/collection_test.js

Specify remote bucket/collection in sync (fixes #451)

---

docs/api.md
src/collection.js
test/collection_test.js

Rename raw methods (fixes #474)

---

docs/api.md
docs/extending.md
fx-src/FirefoxStorage.js
src/KintoBase.js
src/adapters/IDB.js
src/collection.js
test/adapters/FirefoxStorage_test.js
test/collection_test.js

Fixes https://github.com/Kinto/kinto.js/issues/393.

Add sqlite filename support to FirefoxAdapter

---

package.json

Prepare version 3.1.0

---

docs/installation.md

This completes the work started by #482.

update SRI hashes

---

package.json

This release fixes a bug in the FirefoxAdapter part (#488) of the Kinto client and updates a few dependencies.
r? @n1k0 @leplatrem

bump version to 3.1.1

---

src/collection.js
test/collection_test.js

Fixes #495. Also includes some fixes for other things that distracted me when I was trying to get the tests to work correctly.
r? @leplatrem @Natim

Return promises

---

.travis.yml

Upgrade to Kinto 3.3.0

---

docs/api.md
src/collection.js
test/collection_test.js

Trigger events on collection operations (ref #490)

---

.travis.yml

Upgrade Kinto Server version.

---

docs/tutorial.md

Following #513, adding bucket and sending the updated title inside a `{data: }` wrapper.

fix #513 - HTTPie invocation

---

.travis.yml

Upgrade to Kinto 4.0.0.

---

docs/installation.md

Second time's the charm...
r? @leplatrem

Update SRIs for 4.0.1

---

package.json

This release fixes a couple of bugs having to do with conflicts.
- Decode conflicts (#525). Otherwise you'd get remotely-transformed versions of records in your local database.
- Fix conflict handling with published deletions (#522). This prevented conflict handling from working correctly when the conflict involved a record that was deleted locally.

Release v4.0.2

---

package.json

This release fixes a bug in the handling of `lastModified` during a certain kind of conflict when using the `SERVER_WINS` conflict resolution strategy.

Prepare release of v4.0.4

---

src/collection.js

refs https://github.com/Kinto/kinto.js/issues/542#issuecomment-246682638 /cc @ptgamr
r=? @ glasserc @leplatrem

Ref #542: Improve Collection#importChanges documentation.

---

src/adapters/IDB.js

Fix safari issue on IDB cursor with empty values

---

.travis.yml

Upgrade tests to kinto 4.3

---

fx-src/FirefoxStorage.js

Unlike Collection#resetSyncStatus, which resets sync status for all records in a collection, this method resets sync status across all collections. Refs: #567.
This is incompatible with #562 so I will probably have to land it again in Gecko, but I thought I'd share it since it seems to work.

FirefoxStorage: add resetSyncStatus

---

package.json

This release:
- Massive refactor of most methods from manually-handled promises to async/await (#538).
- Updates the documentation with a "NOP" schema example for use when you don't really need an `idSchema` (#533).
- Optimize `collection#list` by doing filtering before putting documents in a list rather than after (#543).
- Upgrades tests to Kinto 4.3 (#573).
- Fix for a puzzling bug involving IndexedDB use on Safari (#549).
- Fixes yet another bug in conflict resolution during `CLIENT_WINS` when using transformers (#570).
- Add a `FirefoxAdapter#resetSyncStatus` that resets sync status across all collections, rather than the one you happen to have gotten your hands on (#571). This is not possible as yet in IndexedDB, so it's only in `FirefoxAdapter` for now.
This might be the last …

Prepare version 5.0.0

---

.travis.yml

We can do this, or wait for 4.3.2. 
@Natim @n1k0 what do you think ?

Use constraints for Kinto installation

---

fx-src/FirefoxStorage.js

This is hopefully the last change I'll have to make before merging #562.
This addresses the parts of #588 that I need right now.
r? @n1k0

FirefoxStorage: Allow connection lifetimes to be managed externally

---

package.json

This release:
- Accept a new `sqliteHandle` in `adapterOptions` in `FirefoxStorage`, and expose `_init` to let it be used sanely (#589).
- Update a bunch of dependencies (#579, #580, #586).
- Constrain dependency on underlying `kinto` when running tests (#584).
r? @n1k0 @leplatrem

Prepare 5.1.0

---

package.json

This release:
- updates a bunch of dependencies (#625, #626, #627, #628, #629, #630, #633, #634, #635, #636)
- refactors some internals of the `sync()` method to allow users to transform local deletes into remote keeps (#640)
This is a major version because it changes one aspect of how remote transformers work. Previously, a remote transformer could return anything for a deleted record, and that record would still be deleted. Now, if a transformer changes a record's `_status`, it will be respected.

Prepare release 8.0.0

---

test/index_test.js

Fix tests after kinto-http 4.3.0 update.

---

package.json
src/adapters/IDB.js
src/collection.js
test/adapters/base_test.js
test/collection_test.js
test/integration_test.js
test/test_utils.js

Obsoletes #677, #678, #679, #680, and #681.
The great advantage of using an automatic formatting tool is that it encodes a specific style that we can normalize all code against, removing needless reformats of our code. Now formatting tool was updated, so we get to needlessly reformat our code.

Update Prettier to 1.2.2

---

package.json

* Update oodles of dependencies -- eslint to 3.19.0 (#639, #644, #654, #655, #658, #665, #667), fake-indexeddb to 2.0.3 (#645, #646, #647, #685, #695), kinto-http to 4.3.3 (#651, #667, #673, #686), esdoc-importpath-plugin to 0.1.1 (#653), babel-istanbul to version 0.12.2 (#656), kinto-node-test-server to version 1.0.0 (#661), sinon to version 2.0.0 (#663), babel-eslint to version 7.2.2 (#672), babel-loader to version 7.0.0 (#683), esdoc-importpath-plugin to version 0.1.2 (#684), http-server to version 0.10.0 (#689)
* Adopt Prettier (#659, #675, #682)
* esdoc: remove esdoc-es7-plugin (#660)
* Suppress lint warnings. (#662)
* Fix remote delete (#692). This breaks API compatibility for the `SyncResultObject.resolved` field. Details are in the updating.md file.

Prepare v9.0.0

---

package.json

Bug fixes:
- No need to push "deleted" resolution (#696).
Dependency updates:
- Update to current location of EventEmitter (#697).
- Update gh-pages to 1.0.0 (#693).

Bump version to 9.0.1

---

docs/installation.md
fx-src/index.js

It's just going to be one of those weeks.

Event emitter typo

---

package.json

Bug fixes:
* Fix EventEmitter typo (#699).

Bump version to 9.0.2

---

package.json
src/collection.js

Update prettier to 1.4.2.

---

package.json
src/collection.js

Update prettier to 1.5.1

---

test/integration_test.js

Could not reproduce the conflicting updates discovered in [Bug 1376618](https://bugzilla.mozilla.org/show_bug.cgi?id=1376618) :(

Investigating Bug 1376618

---

.babelrc

Remove async/await transpilation in Firefox

---

package.json

Expand dependency range for kinto-node-test-server

---

.pre-commit-config.yaml
docs/contributing.md
package.json

This is the same as https://github.com/Kinto/kinto-admin/pull/445 but
for this project.

Use pre-commit

---

package.json
test/collection_test.js

chore(package): update sinon to version 3.2.0

---

package.json
src/adapters/IDB.js
test/adapters/IDB_test.js
test/adapters/base_test.js
test/collection_test.js
test/index_test.js
test/integration_test.js
test/utils_test.js

Update prettier to v1.7.1

---

package.json
test/adapters/IDB_test.js
test/adapters/base_test.js
test/collection_test.js
test/index_test.js
test/integration_test.js
test/utils_test.js

Greenkeeper/prettier 1.7.2

---

package.json
src/collection.js
test/integration_test.js

This should fix #780 and hopefully #781.

Update prettier to 1.8.1

---

docs/api.md

String#contains does not exist.

Use String#includes instead of String#contains.

---

.babelrc
fx-src/index.js
fx-src/jsm_prefix.js
package.json
src/adapters/IDB.js
src/collection.js
src/utils.js

This is similar to https://github.com/Kinto/kinto-http.js/pull/273, but for this library.

Firefox updates

---

package.json

- Remove object-rest-spread transpilation for Firefox (#796).
- Remove IDB#resetSyncStatus (#774).
- Allow passing `localFields` when creating new collection (#785).
- Fix esdoc generation (thanks @zakaluka) (#773).
- Documentation updates (thanks @zakaluka @francois2metz) (#775, #778, #789).

Prepare 11.0.0

---

src/collection.js
test/collection_test.js
test/integration_test.js
test/kinto.ini

Pull every pages during sync (fixes #355)

---

package.json

* Add IndexedDB support in Firefox export (fixes #731) (#733)
* Pull every pages during sync (fixes #355) (#801)
* Add support for deleteAll method (#799) (thanks @agawish)

Bump 11.1.0

---

src/collection.js
test/collection_test.js

Fix SyncResultObject performances using a Map (fixes #806)

---

package.json

* Fix SyncResultObject#add to be more performant. Previously it had quadratic behavior. Now we use a Map to track IDs we've already seen (#807).

Prepare 11.1.1

---

src/collection.js

This implementation is inspired by Florian in
https://reviewboard.mozilla.org/r/238290/#review244208.

Simplify add() implementation

---

package.json

* Clean up SyncResultObject#add based on feedback from Florian Quèze (#809).

Prepare 11.1.2

---

src/collection.js
src/utils.js
test/collection_test.js
test/utils_test.js

Relax record id validation according to server (fixes #824)

---

fx-src/index.js

See https://bugzilla.mozilla.org/show_bug.cgi?id=1464548

Load fetch and indexdb lazily

---

docs/upgrading.md
src/adapters/IDB.js
test/adapters/IDB_test.js

Improve data migration infos and safety

---

package.json

**Bug fixes**
- Add safety check for legacy DB detection (#846)
- Improve data migration (#840)
**Internal changes**
- Update babelify to the latest version 🚀 (#844)
- chore(package): update babel-loader to version 8.0.0 (#843)
- chore(package): update babel-eslint to version 9.0.0 (#842)
- Switch to `sinon.createSandbox()`

Bump v12.0.1

---

package.json

* Update SRIs
* Explicitly depend on @babel/runtime (#850)

Bump 12.0.2

---

fx-src/index.js

Tested in Gecko xpcshell tests

Gecko: use lazy imports

---

src/adapters/IDB.js
src/utils.js

I wanted to avoid in place mutation, but we iterate the list of DB results, so I thought it was acceptable.

Improve readability and performance in IDB and utils

---

src/collection.js
test/collection_test.js

Id like to help with this issue. I followed the advice posted in the original issue just to start. Im wondering what exactly is needed to resolve this. I only added the tests to figure out the direction i should be heading. Any advice would be helpful. Thanks !

Provide key-value store id schema(#558)

---

docs/api.md
src/adapters/IDB.js
src/adapters/base.js
src/collection.js
test/adapters/IDB_test.js
test/collection_test.js

Support sync of collection metadata

---

src/collection.js
test/collection_test.js

Fix localFields

---

package.json

* Respect `localFields` when deciding whether or not to mark a record as `"updated"` (#990).

Bump v12.4.3

---

src/adapters/IDB.js
src/collection.js
test/adapters/IDB_test.js
test/collection_test.js

Before
https://perfht.ml/2WVRfsq
After
https://perfht.ml/2WWcfz1

Import changes in batches

---

docs/api.md
src/collection.js
test/collection_test.js
test/integration_test.js

Add a PULL_ONLY strategy

---

fx-src/index.js
src/KintoBase.js
src/collection.js
src/index.js
test/collection_test.js
test/kintobase_test.js

Fix #1041
In Gecko this would save us 35% of cost for the first call to Remote Settings

Fix #1041: load kinto-http lazily

---

src/adapters/IDB.js

Fix #1043
@asutherland is it required on other requests as well? like database open/delete etc?

Fix #1043: Reject when transaction is aborted

---

docs/api.md

Updated some of the code examples as described in #817

Updates api.md to have more concise code examples

---

docs/api.md
docs/extending.md
docs/index.md
docs/tutorial.md

Hello everyone,
I completed #817. Feel free to tell me if something is missing or if I did something wrong.
I hope you find my contribution helpful!

Rewrite examples with promises to async/await

---

docs/upgrading.md

This PR adds notes to the upgrading guide on how to upgrade to v13.

Add notes on updating to v13

---

src/index.ts

This PR exposes some types that are useful when writing new storage adapters. Exposing these types will allow me to publish a version of `kinto` that works on React Native.

Expose types useful for creating adapters

---

package-lock.json
package.json
test/setup-globals.ts

This PR updates `fake-indexedb` v4.

upgrade to fake-indexeddb v4

---

.eslintrc
src/KintoBase.ts
src/adapters/IDB.ts
src/collection.ts
src/http/base.ts
src/http/collection.ts
src/http/http.ts
src/utils.ts
test/adapters/IDB_test.ts
test/collection_test.ts
test/http/api_test.ts
test/http/bucket_test.ts
test/http/collection_test.ts
test/http/http_test.ts
test/http/integration_test.ts
test/index_test.ts
test/integration_test.ts
test/test_utils.ts

Fix some eslint checks present in mozilla-central
