Kinto/kinto.js

- README.md
- src/collection.js
- src/index.js
- test/index_test.js
Our current `Cliquetis#collection` returns a Promise, which makes users writing a bunch of boilerplate for no obvious reason:
```js
var db = new Cliquetis();
db.collection("articles").then(function(articles) {
return articles.save({title: "foo"});
}).then(…);
```
This patch updates this method so it directly returns a `Collection` instance, which will ensure for every of its method calls that the db is opened, resulting in a much more lighweight usage:
```js
var db = new Cliquetis();
db.collection("articles").save({title: "foo"}).then(…);
```
r=? @leplatrem
> Simplified Collection API.

- README.md
- demo/demo.js
- demo/index.html
- docs/api.md
- docs/hacking.md
- docs/index.md
- docs/tutorial.md
- mkdocs.yml
- package.json
- src/index.js
- test/collection_test.js
- test/index_test.js
There's been some confusion around the scope of Cliquetis, which in its current form is much more of a Kinto client than a Cliquet one. We should rename the project to reflect the situation and avoid creating more confusion.
> Rename project to kinto.js

- README.md
Test:
[![Build Status](https://travis-ci.org/mozilla-services/kinto.js.svg?branch=master)](https://travis-ci.org/mozilla-services/kinto.js) [![Coverage Status](https://coveralls.io/repos/mozilla-services/kinto.js/badge.svg?branch=master)](https://coveralls.io/r/mozilla-services/kinto.js?branch=master) [![](https://readthedocs.org/projects/kintojs/badge/?version=latest)](http://kintojs.readthedocs.org/)
> Adding the documentation badge in the readme.

- README.md
- docs/hacking.md
- docs/index.md
- package.json
After speding a little while trying to come with a patch for [isparta](https://github.com/douglasduteil/isparta) to stop marking command results are okay [while they were actually failing](https://github.com/douglasduteil/isparta/issues/48), I decided we should simply drop coverage support from our continous integration process.
We shall abviously consider readding support for this if the issue is fixed someday.
> Refs #74 - Removed coverage from continuous integration.

- docs/api.md
This should be enough to point developers in the right direction, a full 'Handling sync rejections' section (listing all possible errors sync can reject) can always be added later.
> Hint at http error reporting in docs example, fix #124

- test/integration_test.js
During the integration test, kinto was spawn with a virgin environment (or an environment containing only the provided variables).
While this ensured that any tester where given the same 'pure' kinto instance, it also (a) prevented them to test it in a custom configuration, (b) force them to set the `KINTO_PSERVE_EXECUTABLE` env variable as `pserve` could not be found anymore using the `PATH` environment variable.
This fix makes sure the provided env argument extends the parent environment instead of overwriting it.
This is linked to #130 and raised some discussion with @ametaireau. Keeping a virgin environment for Kinto may be wanted. In particular, the environment is used by the tests to communicate with the Kinto instance and, as a result, will raise uncontrolled behaviour if a user …
> Fix test failing when KINTO_PSERVE_EXECUTABLE is not set in the env.

- docs/hacking.md
This helps to setup the environment to run the tests. It seems that node isn't able to find the pserve that's in the path when run with some specific shells.
cc @quentinroy
> Add instructions on how to run functional tests.

- docs/api.md
- docs/limitations.md
- package.json
**Wait for https://github.com/Kinto/kinto/pull/156** (or some links will be broken)
Since *Cliquet* is only a building block of the Kinto server, it should not be mentionned at all in Kinto.js docs.
We noticed that this introduces a huge confusion between Cliquet and Kinto, and we'll be working on that clarification.
A first step is to remove every explicit mention of Cliquet in Kinto.js docs.
> Remove mentions of Cliquet

- docs/api.md
- docs/limitations.md
While working on the [kinto boiler plate app](https://github.com/Kinto/kinto-react-boilerplate), I realized that I misunderstood the meaning of ``CLIENT_WINS``. 
This PR is an attempt to clarify that **incoming** conflicts still may occur with the `CLIENT_WINS` policy.
@Natim @ametaireau @n1k0 r?
> Clarify docs about having to resolve incoming conflicts

- src/http.js
Refs #68, #82; for now backoff header handling is not performed when we receive 304 responses, because of https://github.com/mozilla-services/kinto/issues/148.
Once this issue is fixed and a new Kinto release is issues, we should remove that exclusion.
> Remove the Backoff header handling exclusion for 304 responses 

- docs/api.md
- src/collection.js
- src/index.js
- test/index_test.js
Refs #113 and preparation patch for #150. r=? @leplatrem @michielbdejong
> Fixes #113 - Expose synchronization strategy constants.

- docs/api.md
I think the section label should be "resolving-conflicts-manually". Do you want me to open an issue first and prefix this commit with "Fixes #xxx - "?
> Section label resolving-conflicts -> resolving-conflicts-manually

- src/collection.js
The statement that this function will reject if it encounters conflict seemed incorrect to me. Also, to say it imports changes, if there is also a function called `importChanges` seemed confusing.
> Correct code comment for `Collection#pullChanges`

- .travis.yml
We should run our integration tests against the very [latest stable](https://github.com/Kinto/kinto/releases/tag/1.4.0) release of Kinto.
r=? @Natim @leplatrem @ametaireau
> Upgraded Kinto to 1.4.0.

- .travis.yml
This is most likely to fix our broken builds, because Kinto 1.4.0 has troubles starting from our test env, while 1.5.0 seems to have fixed the situation.
> Upgraded Kinto to 1.5.0.

- src/index.js
- test/integration_test.js
Looks like the Api object only depends on Kinto-level options, not on Collection-level options.
So is this safe this way? @n1k0 
(didn't run tests yet)
> Fixes #169 - Instantiate Api only once

- docs/hacking.md
Also added use of \`pwd\` in `KINTO_PSERVE_EXECUTABLE` instructions, so that it's automatic.
Btw, I could not find any mention of `KINTO_PSERVE_EXECUTABLE` in `.env/`, `.venv/` or `./venv/` - so is this step not always necessary by definition?
> 'git co' -> 'git clone' in install instructions

- docs/extending.md
- src/adapters/IDB.js
- src/adapters/LocalStorage.js
- src/adapters/base.js
- test/_setup.js
- test/adapters/IDB_test.js
- test/adapters/base_test.js
- test/adapters/localStorage_test.js
Refs https://github.com/Kinto/kinto.js/pull/219#issuecomment-151587615
Basically we now add `open` and `close` methods to the `BaseAdapter` base class, so implementers must implement them.
Also is now exposed a `Collection#close` method so apps using adapters needing explicit closing can call that (opening is always done implicitly when a first operation is scheduled for execution).
cc @rnewman 
@mozmark: would this work for you?
> Exposed open() and close() methods to the BaseAdapter interface.

- src/collection.js
- src/utils.js
- test/utils_test.js
We're now accepting uuid formats matching the cliquet spec. But we're still creating UUID4 by default.
r=? @natim @leplatrem @almet
> Relaxed UUID validation.

- docs/api.md
- fx-src/FirefoxStorage.js
- src/adapters/IDB.js
- src/adapters/LocalStorage.js
- src/adapters/base.js
- src/collection.js
- test/adapters/IDB_test.js
- test/adapters/base_test.js
- test/adapters/common.js
- test/adapters/localStorage_test.js
- test/collection_test.js
For some of the Mozilla platform use-cases, it's desirable to have the ability to import initial data. Since we only need it here, for the time being, we can prototype the idea in the Firefox storage adapter and apply what we learn to the other adapters.
> Add support for db.import

- fx-src/FirefoxStorage.js
- fx-src/index.js
- src/collection.js
When implementing more tests cases for the `loadDump()` feature, we faced a couple of problems releated to JSM (ref #273)
This diff appears to solve them properly.
We take any feedback! :)
@mozmark r?
> Fix JSM compatibility for Firefox adapter

- docs/releasing.md
- esdoc.json
- package.json
- src/collection.js
Used to fail with this:
```
error: could not parse the following code. if you want to use ES7, see esdoc-es7-plugin(https://github.com/esdoc/esdoc-es7-plugin)
/home/mathieu/Code/Mozilla/kinto.js/src/collection.js
676|         // Merge outgoing conflicts into sync result object
677|         syncResultObject.add("conflicts", conflicts);
678|         // Reflect publication results localy
679|         const missingRemotely = skipped.map(r => ({...r, deleted: true}));
680|         const toApplyLocally = published.concat(missingRemotely);
681|         return Promise.all(toApplyLocally.map(record => {
682|           if (record.deleted) {
```
@n1k0 r?
> Fix parsing of ES7 code in esdoc

- demo/demo.js
- docs/api.md
- docs/tutorial.md
- src/api.js
- src/collection.js
- src/utils.js
- test/collection_test.js
- test/utils_test.js
Took the easiest way to allow passing the remote to `#sync()`. Works, but ugly, as I'm mutating the api instance during the time of the sync flow execution :/ That's the price to pay for strict BC.
Later we'll move the whole sync flow to its own module, so that's a temporary situation (famous last words).
r=? @leplatrem
> refs #257: Allowing defining the remote endpoint in #sync().

- docs/api.md
- src/collection.js
- test/collection_test.js
- test/integration_test.js
WiP; refs #286, #309.
This adds support for a new `patch` option to `Collection#update()`, so one can simply augment an existing record with supplementary properties or replace the values of existing ones.
Feedback=? @michielbdejong
> Allow patching a record using Collection#update().

- src/collection.js
- test/collection_test.js
- test/integration_test.js
Here's what happens without this patch:
* Start an empty Kinto server
* Sync (collection is empty)
* Create record '12345678-1234-1234-1234-1234567890ab' as `{ value: 'a' }`, and sync (record is created remotely)
* Update record '12345678-1234-1234-1234-1234567890ab' to `{ value: 'b' }`, and sync
Expected: the record is updated remotely
Actual:
* First, data is fetched, and (due to https://github.com/Kinto/kinto.js/issues/306 I think?) record  '12345678-1234-1234-1234-1234567890ab' is updated to `{ value: 'a' }`, but that's probably unrelated here.
* Now `gatherLocalChanges` notes the update to `{ value: 'b' }` and adds it to `toSync`, but without `last_modified`.
* Since there is not `last_modified` on `updatedRecord`, the `If-None-Match: *` header is set
* This request fails, of course. …
> Set last_modified on updated record if missing

- .babelrc
- package.json
Thanks @n1k0 , tt works like a charm :) 
By default the default environment `development` applies everywhere and produces es5.
For `firefox`, we output es6 with commonjs for browserify and for-of loops transpiled.
@mozmark r?
> Leverage Babel environment in .babelrc (fixes #316)

- fx-src/FirefoxStorage.js
- src/adapters/IDB.js
- src/adapters/base.js
- src/collection.js
- test/adapters/IDB_test.js
- test/collection_test.js
Small benchmark: 4500 records in local store. None of them changed.
Before (1000+):
After (<50):
> Use IndexedDB indexes on gatherLocalChanges()

- docs/installation.md
r? @mozfreddyb
```
$ curl https://npmcdn.com/kinto@1.2.0/dist/kinto-1.2.0.js | openssl dgst -sha384 -binary | openssl enc -base64 -A ; echo
rn0oNAl6rWA/VxPyRivzf9Ad+LrmqnnaO1V6lujBhVWnA90pJDVR5XFR3GRGx/mM
$ curl https://npmcdn.com/kinto@1.2.0/dist/kinto-1.2.0.min.js | openssl dgst -sha384 -binary | openssl enc -base64 -A ; echo
aaty4B6Fzw+pZ9DbNdrlGsFu9f8x06+N0aCAXCn1QMpWVgB79PC9KSdWqqagm6E9
$ curl https://npmcdn.com/kinto@1.2.0/dist/kinto-1.2.0.noshim.js | openssl dgst -sha384 -binary | openssl enc -base64 -A ; echo
WeYjSGsF3rAvWa7r3+tDr/AUzIa3fiWP/xditLak/kw76bQfUtENbx3VhaytTrK+
> Fix SRI hashes in documentation (fixes #324)

- .travis.yml
- test/integration_test.js
@michielbdejong I tried to reproduce #306 but can't find any problem.
I updated the kinto server to 1.11.2 which includes the fix about `ETag` in 304 responses.
Please take over the branch if you know how to highlight the problem :)
Otherwise it's not a bad idea to merge it IMO.
> Functional test when no change on server (ref #306)

- docs/api.md
- docs/extending.md
- src/KintoBase.js
- src/collection.js
- test/collection_test.js
- test/integration_test.js
This adds the concept of collection transformers.
I haven't updated the documentation because I'm not sure about the concepts we want to expose, as mentioned in #154 & #153.
The documentation states that transformers should be able to encode and decode, but I'm not sure that should be the case for what's implemented here as "collection transformers". I'm happy to have any feedback on the naming (and of course the implementation).
If we chose to go with the "transformers" approach (and still not have decode / encode), then the documentation will need to be updated to explain what a collection should be.
For what it's worth, the first version of this code was implemented with "decode" and "encode" functions, but I couldn't see why we were needing them, so I removed them and passed a …
> Add collection transformers.

- package.json
I realized that currently there was no easy way to obtain the version of the client embedded in Firefox.
I added a `echo $npm_package_version` in the `run dist-fx`. But maybe we could generalize it to every builds?
@mozmark r?
@n1k0 feedback?
The output looks like so:
```js
/*
*
* Licensed under the Apache License, Version 2.0 (the "License");
[...]
* limitations under the License.
*/
/*
* This file is generated from kinto.js - do not modify directly.
*/
this.EXPORTED_SYMBOLS = ["loadKinto"];
/*
* Version 1.2.0
*/
(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.e
```
> Output Kinto client version in Moz build for Firefox

- package.json
- src/index.js
When having kinto.js as a dependency in another project using the Babel polyfill as well, we get an `only one instance of babel/polyfill is allowed` error, because that polyfill can [only be imported once](https://phabricator.babeljs.io/T1019).
This maintenance patch for the 1.2-maintenance branch fixes this, and we'll publish a 1.2.1 patch release when this is landed onto that branch.
Note that we should issue the fix for master as well, though in a next PR.
r=? @leplatrem
> [1.2] Ensure a single instance of babel-polyfill is imported.

- package.json
- src/collection.js
- src/utils.js
Use deeper instead of assert, which is shipped entirely by browserify.
(as an example, it reduces the gecko build by 25Ko)
I had to blacklist `buffertools` because of this: https://github.com/othiym23/node-deeper/pull/4
@n1k0 r?
> Switch from assert to deeper

- docs/tutorial.md
I found the broken link.
'http://kinto.readthedocs.org/en/stable/installation.html' is not exist.
> Fix broken link to 'installation'

- fx-src/jsm_prefix.js
pair=@n1k0
Spawned https://github.com/Kinto/kinto.js/issues/402 to go further on this
> Add mock for Buffer in Gecko client (fixes #400)

- test/collection_test.js
This is something I encountered when I was working on the conflict
resolution thing.
Our stubs should return the same kinds of data that an actual server would.
> add last_modified to all tests

- src/collection.js
- test/collection_test.js
> Avoid redownloading our own changes (fixes #144)

- docs/api.md
- src/collection.js
- test/collection_test.js
This is another approach to solve #443, #444, and #445. Unlike #447, which adds options to existing methods, this PR introduces new methods which do not support the old use cases at all but simply support what I need -- raw access to a key-value store without application-level access. These methods are called `getRaw()`, `put()`, and `deleteAny()`. I re-use code from the existing `get()` and `update()` methods by extracting them (`get()` now just calls `getRaw()` and then throws if it's missing; `update()` calls `_updateRaw()`). This seemed better than copying and pasting the entire methods, although I'm open to doing that if the auxiliary methods seem too complicated. I decided not to refactor `delete()`, since very little code is shared.
r? @n1k0
> Richer methods 2

- fx-src/FirefoxStorage.js
- src/adapters/IDB.js
- src/collection.js
- test/adapters/IDB_test.js
- test/collection_test.js
... instead of records. This matches both the underlying semantics of
the operation (which is fetching these records) as well as the use case
I'm about to implement (which only has access to the IDs).
r? @leplatrem @n1k0
> Adapter#execute preload option takes IDs

- docs/api.md
- src/collection.js
- src/utils.js
- test/collection_test.js
This is a proof-of-concept of transaction support at the Collection layer (#467). I would like to solicit feedback.
The approach in this branch is to wrap the underlying DB/adapter transaction using a CollectionTransaction and slowly move Collection methods into the CollectionTransaction class. Rather than delete the existing methods, we leave them as "atomic" operations that wrap them in an immediate `execute`.
So far I have moved `get`, `getRaw`, `delete`, and `deleteAny`. There remain `put`, `update`, `create`, and maybe some others.
This approach makes each of the CollectionTransaction functions synchronous, which means that their output can be returned by the user's function however it wants. So example use might be:
```javascript
collection.execute(txn => {
return [ …
```
> Add transactions to Collection layer (fixes #467)

- fx-src/index.js
The intended shape of the expanded options is:
```
{
idSchema: {
generate: ....
validate: ....
},
... other options
}
```
I don't see an easy way to test this because it calls its superclass,
which isn't easy to stub or mock.
This is one of two changes that need to be made to get FF tests to pass (the other is in the FF test itself).
r? @leplatrem @n1k0 @Natim @lavish205
> restore idSchema in fx-src

- package.json
This release fixes a bug with the `incoming-changes` hook which prevents hooks from returning Promises (#495, #496).
r? @leplatrem
> Prepare 3.1.2

- docs/api.md
add a note about sorting according to a single field
> documentation: correct typo in list sorting

- docs/api.md
- src/collection.js
- test/collection_test.js
The docs say that remote transformers must preserve `id`. I can't figure out why that should be the case, except that it enables a tiny optimization where we don't have to run the transformer on deleted records. This might be intentional, in case we wanted to spare client code from handling deleted records specially.
In my use case, I'd like to obfuscate record IDs on the server so that they don't leak information about what application is using Kinto locally.
> Transform even deleted records

- package.json
This release causes remote transformers to be invoked even on deleted records, and thereby allows you to write a remote transformer that mutates record IDs (#510). It is a backwards-incompatible change because now a remote transformer must handle deleted records, which are missing all the normal fields you would expect from your records.
There are also some fixes to documentation errors (#515, #514) and updates of dependencies (#508, #512, #509, #502).
> Preparing 4.0.0

- demo/demo.js
The demo wasn't working for me, failing that "err.message.contains is not a function". I believe that is because the function is called `includes` (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes).
> Use correct ES6 name for string function

- package.json
I made a mistake in releasing 4.0.0 and published something wrong to NPM. This release is just a rebuild of 4.0.0, which shouldn't be used.
> Prepare 4.0.1

- src/collection.js
- test/integration_test.js
This fixes an issue brought to our attention by @ochameau (thanks!), where a conflicting remote deletion couldn't be properly handled during the publication part of the synchronization flow.
Basically kinto-http.js, when aggregating results from a batch operation, exposes the request data body as the local (initial) version of the conflict; but in the case of deletion, there is no request body sent.
This patch simply ensures there's data available in the received `local` part of the conflict object, and fallbacks to `{}` if there's none.
r=? @leplatrem @glasserc
> Fix conflict handling with published deletions.

- src/collection.js
- test/integration_test.js
The test in the first commit fails. A similar bug exists for SERVER_WINS strategies, obviously, but I haven't written it yet. The tests in the second commit don't fail, but I had already written them and I want to make sure they don't start failing when I apply the fix.
> Decode conflicts

- src/utils.js
This is useful when the Object constructor might differ from object to
object. This has been true for me when hacking on Gecko -- the objects
that make it to the deepEqual function are instances of Object (from the
kinto-http-client scope), but the reference Object points to
Object (from the kinto-offline-client scope). We might also expect this
sort of thing to come up when someone uses Kinto in a WebExtension; the
scope of the WebExtension will be different from the scope of the code
running on the page. Instead of using the "instanceof Object" check, use
the "typeof" check. Unfortunately, because JavaScript, null and
undefined also have typeof "object", so try to rule out falsy things
explicitly.
r? @n1k0
> deepEqual: Remove instanceof Object check

- package.json
This addresses a bug where conflicts weren't being resolved as "equal" in certain runtime environments (i.e. Gecko). See #529 for details.
r? @n1k0
> Prepare version 4.0.3

- docs/installation.md
- package.json
Since the version of the webpacked assets is not reproducible, use curl to fetch the version of the asset from npmcdn and use that to compute the SRI. Also, add a note in the header of the table to show what version the SRIs correspond to.
r? @Natim @n1k0 @elelay
> Compute SRIs from npmcdn and add version to table

- src/collection.js
- test/integration_test.js
I wasn't sure what the correct behavior for manual conflict resolution
was, but I'm pretty sure that we should update lastModified for all of
these cases. So far, we only do so in three of them.
This is a test case illustrating the failure in #535.
> Introduce failing test for updating lastModified

- fx-src/FirefoxStorage.js
- src/adapters/IDB.js
- src/utils.js
- test/adapters/FirefoxStorage_test.js
- test/utils_test.js
Code for #534 : don't put documents in the results to be discarded later but filter them earliest.
I thought it would give a moderate performance boost and indeed get 8% time improvement and no memory change (1% not significant)  for a query rejecting every document.
My test code (oldTickets contains 7626 documents, none match)
```
function perfTest(cnt, acc){
if(cnt <= 0){
avg = acc.length && (acc.reduce(function(s, x) { return s + x; }, 0) / acc.length);
console.log("perfTest avg=", avg);
}else{
if(cnt % 10 === 0){
console.log("perfTest", cnt, "remaining");
}
before = new Date();
oldTickets.list({filters: {status: "open"}}).then(function(){
after = new Date();
//console.log("list() took", after - before, "ms");
acc.push(after - before);
perfTest(cnt - 1, acc);
});
}
}
perfTest(50, []); …
```
> 534: filter documents as they are retrieved from IDB

- docs/api.md
- docs/tutorial.md
- package.json
- src/collection.js
- test/collection_test.js
- test/integration_test.js
This pull-request relies on kinto-http.js 2.5.1 
The `skipped` attribute in sync result now contains the record id that was skipped instead of a plain 404 error response body.
An integration test now executes a skipped remote deletion.
@n1k0 r?
> Fix skipped remote deletion (fixes #540)

- .babelrc
- package.json
After #548, running the demo fails with `ReferenceError: regeneratorRuntime is not defined`
I added the necessary Babel stuff. But this makes the build bigger :/
Before:
```
-rw-rw-r--  1 mathieu mathieu 1,2M sep 16 11:01 kinto.js
-rw-rw-r--  1 mathieu mathieu 250K sep 16 11:01 kinto.min.js
-rw-rw-r--  1 mathieu mathieu  86K sep 16 11:01 kinto.noshim.js
-rw-rw-r--  1 mathieu mathieu  88K sep 16 11:01 moz-kinto-offline-client.js
```
After:
```
-rw-rw-r--  1 mathieu mathieu 1,3M sep 16 11:04 kinto.js
-rw-rw-r--  1 mathieu mathieu 286K sep 16 11:04 kinto.min.js
-rw-rw-r--  1 mathieu mathieu 147K sep 16 11:04 kinto.noshim.js
-rw-rw-r--  1 mathieu mathieu 138K sep 16 11:04 moz-kinto-offline-client.js
```
What do think ?
Personnally, I think that having async/await in the codebase really helps …
> Add generator runtime for async/await

- src/collection.js
- test/integration_test.js
I don't remember if I didn't add this test the first time around because it wasn't working, or because I didn't think it could not be working, but add the test and add the fix.
@n1k0 @leplatrem r?
> Encode conflict resolutions during CLIENT_WINS (fixes: #569)

- package.json
This merges #562, which is a major version change because it removes the
Firefox storage adapter. This code is specific to Gecko and will move to
that repository.
> Prepare version 6.0.0

- docs/api.md
- src/collection.js
- test/collection_test.js
That is a trivial addition.
I think it is useful for pluggabilty and flexibility, but I feel I could be convinced otherwise :)
For example:
```js
const kinto = new Kinto();
kinto.events.on("sync:success", function(result) {
telemetry.count("success");
});
kinto.events.on("sync:error", function(result) {
telemetry.count("error");
});
collection.sync();
```
Versus:
```js
const kinto = new Kinto();
collection.sync()
.then(() => telemetry.count("success"))
.catch(() => telemetry.count("error"));
```
Thoughts ?
> Add sync events

- package.json
babel 6.22.0 and 6.22.1 have a bug that got fixed in 6.22.2 -- see https://github.com/babel/babel/blob/85eec9ffef9f2defbcc4cce29440c5ef230708d2/CHANGELOG.md#bug-bug-fix. I don't see a Greenkeeper PR for this version, so I'm opening my own.
Deprecates: #623, #631.
> Update babel-cli to 6.22.2

- package.json
Deprecates #624, whose failure won't reoccur because of #633.
> Update babel-core to 6.22.1

- docs/api.md
- src/collection.js
- test/collection_test.js
- test/integration_test.js
Try to fix #638.
A remote transformer normally maps local deletes to remote deletes and local updates/creates ("keeps") to remote keeps. However, we can also imagine remote transformers that map "across" these categories -- that is, mapping local deletes to remote keeps, or local keeps as remote deletes. This PR implements the first of these categories as part of fixing https://bugzilla.mozilla.org/show_bug.cgi?id=1333810, https://bugzilla.mozilla.org/show_bug.cgi?id=1333814, and https://bugzilla.mozilla.org/show_bug.cgi?id=1333818.
Note that currently mapping local keeps to remote deletes isn't going to work very well. Remote deletes on the Kinto server become tombstones, which don't have a lot of information, and probably won't have enough information to recreate the local keep. This …
> Encode local deletes as remote keeps

- esdoc.json
- package.json
- test/integration_test.js
- test/kinto-5.3.6.ini
- test/kinto.ini
Per https://github.com/esdoc/esdoc/issues/390, esdoc-es7-plugin is
deprecated and esdoc has itself grown functionality equivalent to
it. Now using esdoc-es7-plugin causes esdoc generation to fail.
Following the fix in the linked issue, just turn on all the options,
since I'm not sure which ones we use specifically.
Thanks tiberiuichim for reporting this issue on Slack.
> esdoc: remove esdoc-es7-plugin

- src/collection.js
I remember we kept `let` assignments in for loops because of an incompatibility in Firefox back in the days, but I believe this has been addressed since then. Can we reintroduce `const` assignments in for loops?
> Suppress lint warnings.

- src/collection.js
- test/integration_test.js
It seems strange to say that this record is "synced", but "deleted" would mean that it was deleted locally and needed the delete to be replicated remotely.
> collection: No need to push "deleted" resolution

- fx-src/index.js
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1356231, devtools is
going away.
This is the same as https://github.com/Kinto/kinto-http.js/pull/190, but for this project.
> Update to current location of EventEmitter

- package.json
- test/collection_test.js
2.3.0 introduced some improvements to stubs of descriptors. `batch` is a
descriptor because of being decorated with @nobatch. But it's a
descriptor whose `get` function itself returns a function, so things are
a little strange.
The fix works on 2.3.2 and on < 2.3.0 but not on [2.3.0, 2.3.1], so bump
the dependency too I guess.
Fixes #708. Supersedes #704.
> Update tests for sinon 2.3.2

- docs/installation.md
I noticed that the install information stating `NodeJS v0.12.x]` is not congruent with what is stated in the `package.json` file,
```
"engines": {
"node": ">=6"
},
```
> Updated required Node version

- docs/contributing.md
Same as my previous PR regarding installation.md, I noticed that the information stating which version is required, [NodeJS v0.12.x] is not congruent with what is stated in the package.json file,
```
"engines": {
"node": ">=6"
},
```
> Updated required Node version in contributing.md

- package.json
This got pinned to a specific version in
3dc778baa1373384a438129a2dcddd62ef402c56 to work around a temporary
breakage that seems to have been resolved at some point in the
intervening 18 months. Most eslint versions have not caused breakage.
Closes #758.
> Turn eslint dependency into range dependency

- test/integration_test.js
Kinto's environment parsing logic runs this through native_value,
which tries to parse it using ast.literal_eval, which interprets the
string "2017-10-30" as the mathematical expression 2017-10-30, which
is 1977.
This code has been in place for a long time so it isn't clear how it
ever worked. ast.literal_eval has behaved this way since at least
2014.
In Kinto 7.x, we stopped using literal_eval for native values and
instead use json.loads, which of course can't parse 2017-10-30, which
leads us to fall back to using the string as a string. So the recent
test failures we've been seeing have only affected Kinto 6.0.4.
One reason why this seems to have been working up until very recently
is that 2017-10-10 is the first date since 2016-12-31 where one of the
"operands" didn't start with a 0, …
> Ensure that KINTO_EOS is a string

- src/adapters/IDB.js
- test/adapters/IDB_test.js
- test/integration_test.js
This is a semiprivate method modeled on the method of the same name in
the Firefox storage adapter.
This is useful when implementing encryption schemes that have
unrecoverable states -- you can wipe the server and resetSyncStatus()
to resend everything you have.
> Add IDB#resetSyncStatus

- package.json
- Remove async/await transpilation for Firefox (#732)
- Add IDB#resetSyncStatus (#767).
- Allow ID schemae to use the record itself when generating its ID (#727).
- Update requirements and dependencies: Sinon is now 4.0.0 or greater (#760, #748, #709), ESLint is now `^4.7.2` (#759, #757, #756, #753, #749, #746, #745, #739, #734, #721), Mocha is now 4.0.0 or greater (#768), Coveralls is now 3.0.0 or greater (#766), Prettier is now 1.7.2 (#765, #762, #751, #725, #714), esdoc-importpath-plugin is now 1.0.1 (#754, #742, #722), babel-eslint is now 8.0.0 or greater (#755), esdoc itself is now 1.0.1 or greater (#741), kinto-node-test-server is now a range dependency of `^1.0.0` (#736), uglifyify is now 4.0.1 or greater (#717), chai is 4.0.1 or greater (#712) and chai-as-promised is now 7.0.0 or …
> Prepare 10.0.0

- src/adapters/IDB.js
- test/adapters/IDB_test.js
Revert 3017452aca9672681c9328ec93853ce472d31faf.
It turns out that there's already a Collection#resetSyncStatus, so
IDB#resetSyncStatus just serves to confuse the user.
The place where I intended to use this, I already accidentally used
Collection#resetSyncStatus, so there truly isn't any need for this
method.
The commit that this reverts got squashed as part of #767, so the
commit ID in this commit may not exist in this repository. Instead,
see 7a23ff9b16f3f85dcc92c1d998b2faa86d367006.
> Remove IDB#resetSyncStatus

- src/KintoBase.js
- test/kintobase_test.js
I've noticed that when creating new collection from `KintoBase` it's impossible to define `localFields` option, My change fixes it.
Example usage:
```js
const kinto = new Kinto()
const collection = kinto.collection('my_collection', {
localFields: ['_status']
})
```
> Add missing `localFields` option when creating new collection

- src/collection.js
- test/collection_test.js
Fixes: #556
Changes the following Files:
1. src/collection.js: Added deleteAll function in two places:
a. As an async function inside Collections class - Takes no parameters -
b. As a function inside CollectionTransaction class - Takes records parameter - to execute the delete transaction and emit "deleteAll" event
2. test/collection_test.js: Added two tests:
a. Inside Events test suite to test for "deleteAll" event
b. Inside #execute test suite to test for the soft delete
All tests are passing.
Also ran cs-format to follow coding style and added the git pre-commit hook
Signed-off-by: Amr Gawish <amr.gawish@gmail.com>
> Add support for deleteAll method

- fx-src/index.js
- fx-src/jsm_prefix.js
- src/index.js
> Add indexeddb support in Gecko export (fixes #731)

- package.json
This is meant to address #849.
> Explicitly depend on @babel/runtime

- src/collection.js
- test/collection_test.js
sync() appears to have some support for a `filters` option, but that
doesn't really make sense since we don't support syncing partial
collections.
> Add support for expectedTimestamp to sync() and pullChanges()

- src/adapters/IDB.js
- test/adapters/IDB_test.js
Fix #862 
I also want to investigate the performance impact depending on the collection size (eg. 100, 1K, 10K records)
> Fix #862: Use getAll() in IDB if no filter is set

- src/adapters/IDB.js
I realized that in #865 I could also have gone further and use `.getAll()` when no filter is used on custom field.
For example, when we gather local changes we want all records whose is status is not "sync".
> Ref #862: use getAll() with indexed fields too

- src/adapters/IDB.js
Ref #870 
This doesn't entirely fix the #870 since we have another place (`Collection.importChanges()`) where the «chaining» could be leveraged. However, because we have an abstraction around storage adapters, we can't do it the same way as for loadDump.
In Gecko RemoteSettings we have a use-case where the dump contains around 1K entries. This PR should help greatly. However we have another use-case where the server contains 1K entries but no dump. For that one, the bottleneck will be in `importChanges`. I propose that we solve it in another PR after we've seen some improvements with this one.
> Ref #870: better bulk insert for IDB loadDump()

- src/adapters/IDB.js
- src/collection.js
- test/adapters/IDB_test.js
I was playing with IndexedDB, trying to punch it in the guts to see how errors would come out for real.
Since we use the error message to detect the type of error we are facing, I thought that prefixing could help us tag the ones coming from the IDB adapter.
> Prefix error messages in IndexedDB adapter

- src/collection.js
- test/collection_test.js
I think this is the cause of https://bugzilla.mozilla.org/show_bug.cgi?id=1551952.
There's an underlying issue here about how options can be passed anywhere but aren't required anywhere, including headers, but fixing that is more complicated. For now, just explicitly pass headers, as is done in e.g. `pullChanges`.
> pullMetadata does not pass auth

- package.json
* `pullMetadata` now passes `headers`. This should fix failures in syncing where authentication appeared to "go missing" in the middle of syncing, for example https://bugzilla.mozilla.org/show_bug.cgi?id=1551952.
> Bump v12.4.1

- src/collection.js
- test/collection_test.js
The calling convention for `getData` is for everything to be in a single `options` argument. Fix this again.
> Fix pullMetadata really

- src/collection.js
- test/collection_test.js
Before:
https://perfht.ml/2Xthz1c
After:
https://perfht.ml/2WVRfsq
--> Time spent in `importChanges()` becomes ridiculous.
> Optimize sync result code

- docs/advanced.md
- docs/api.md
- docs/tutorial.md
Hi,
As promised in my previous PR, I updated documentation examples with arrow functions. I left normal `function`s when I thought it was clearer.
I also updated `var` with `const` and added `const` to some global variable declarations.
I hope you find it useful.
> Update documentation examples with arrow functions and const

- src/adapters/IDB.js
- test/adapters/IDB_test.js
I'm working on https://bugzilla.mozilla.org/show_bug.cgi?id=1617133 in Firefox, and there might be a few adjustments to do in kinto.js. So far, draft status :)
> Keep original error name in IDB adapter

- .github/workflows/size.yml
This PR adds a GitHub workflow that will report the compressed size of our bundles on each PR made from a branch in this repo. (Sadly due to the way GitHub Actions handles forks, it won't report when a PR is made from a fork. I have an idea on how we might make that a little better, but for now this is acceptable.
> Add compressed-size-action workflow

- docs/api.md
- docs/extending.md
- src/KintoBase.ts
- src/adapters/base.ts
- src/adapters/memory.ts
- src/collection.ts
- src/index.fx.ts
- src/index.ts
- src/utils.ts
- test/collection_test.ts
- test/index_test.ts
- test/kintobase_test.ts
- test/utils_test.ts
This PR improves the typing support for adapters, decoupling the dependence on the IDB adapter.
This contains a **breaking change** in the way adapters are provided to the client. Instead of passing the class as the adapter property, callers will now need to pass a function that returns an instantiated instance of the adapter.
```ts
// Old
const client = new Kinto({ adapter: IDB });
// New
const client = new Kinto({ adapter: (cid, options) => new IDB(cid, options) }
```
This allows us to support arbitrary constructors for storage adapters.
This PR also includes a new in-memory storage adapter, intended only for documentation purposes. It's not exported in the bundle, so users won't have access to it. It serves as an easier-to-understand implementation so that people who want to write …
> [semver major] Improve storage adapter support

- CHANGELOG.md
- src/KintoBase.ts
- src/collection.ts
- src/index.ts
- src/types.ts
- test/index_test.ts
- test/integration_test.ts
This PR replaces our usage of EventEmitter with an interface with the following shape:
```ts
interface Emitter {
emit(type: string, event?: any): void;
on(type: string, handler: (event?: any) => void): void;
off(type: string, handler: (event?: any) => void): void;
}
```
This allows the consumer to provide their own emitter, or opt not to. For users who opt to use a small emitter like [mitt](https://github.com/developit/mitt), this should result in a decently smaller bundle size.
Fixes #1301
> Replace EventEmitter with interface and make it optional

- .github/workflows/size.yml
- CHANGELOG.md
- package.json
- rollup.config.js
- tsconfig.json
This PR makes a few packaging updates to support our v14 release.
- Emit TypeScript declarations
- Use ES2017 for our browser and CommonJS builds
- Only package important files for npm
- Emit non-minified version of browser bundle
> Infrastructure updates for v14

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
This PR adds new GHA workflows to mirror what we're testing in Travis (basically a new Linux integration workflow and a workflow to check Prettier/ESLint).
> Migrate Travis CI steps to GitHub Actions

- src/collection.ts
- src/index.ts
- src/types.ts
This PR exports the following types:
- `Collection`: The class representing a Kinto collection
- `CollectionSyncOptions`: The options provided to the `Collection.sync` method
- `Conflict`: The API response representing a conflict that occurs during a sync operation
> Export type Collection, CollectionSyncOptions, and Conflict

- src/adapters/IDB.ts
- src/utils.ts
- test/adapters/IDB_test.ts
This PR updates the signature for `omitKeys` from
```ts
export function omitKeys<
T extends { [key: string]: any }
>(obj: T, keys: string[] = []): Partial<T>
```
to
```ts
export function omitKeys<
T extends { [key: string]: unknown },
K extends string
>(obj: T, keys: K[] = []): Omit<T, K>
```
After this change, the compiler detected that we were incorrectly accessing a `length` property on an object:
```
if (remainingFilters.length === 0) {
// Property 'length' does not exist on type 'Pick<{ [key: string]: any; }, number>'
```
Because JavaScript objects don't have a `length` property, I was curious how this worked. After checking test coverage, I saw that this particular statement would always evaluate to `false` given that the `remainingFilters` object never had a `length` property to …
> Make omitKeys more type-safe

- .github/workflows/browsers.yml
Fixes #1466 
Firefox tests are flaky on Windows, so this PR switches to running our browser integration tests on Linux for better stability.
> Run browser tests on Linux

- package-lock.json
- package.json
This PR ensures that one of our dependencies, `intern`, is provided with an up-to-date version of `ts-node` that's compatible with recent versions of TypeScript. It accomplishes this by using the new npm v8 feature `overrides` to ensure that the version of `ts-node` provided to `intern` is always the same version as specified in our dependencies. This is necessary since TypeScript 4.7 introduced a breaking change that was fixed in `ts-node` `v10.6.0`, which is not compatible with the version requested by `intern` (`~10.0.0`).
> fix(deps): pin ts-node version

- fx-src/jsm_prefix.js
- src/http/index.fx.ts
There've been several patches landed in Moz Central that have directly updated `kinto-http-client.js`. These changes all have to do with the way `ChromeUtils` modules are imported.
This commit makes it so our generated files contain these changes.
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1777486
https://bugzilla.mozilla.org/show_bug.cgi?id=1792341
> Update `ChromeUtils` module imports

- .github/workflows/browsers.yml
Intern, our testing library, is not currently compatible with the latest LTS release of Node (v18) which is included by default in GitHub Actions runners. This PR pins the version of Node used for our browser tests to v16 to get them working again. Other workflows are unaffected as the bug only impacts the Selenium-based browser testing flow in Intern.
> Pin Node version used in browser tests

- package-lock.json
- package.json
This PR updates all dependencies to their latest version that's allowed by the semver range specified in `package.json`. This was achieved by running `npm update`.
> update dependencies to latest in current semver range

- .github/dependabot.yml
This PR switches our Dependabot config from updating weekly to updating monthly. This is mainly because the `@typescript-eslint` packages are updated weekly on an automated schedule, so that guarantees that there will be PRs every week. Given the amount of attention maintainers can pay, I think it's better that we get monthly Dependabot updates and a full month to resolve them before the next round of PRs.
> update dependabot monthly

- .github/workflows/browsers.yml
- intern.json
This PR disables Chrome browser tests since Intern is unable to download the appropriate chromedriver due to the recent introduction of the [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) program.
> ci: disable browser tests for chrome

- src/http/collection.ts
- src/http/requests.ts
- test/http/requests_test.ts
Option was dropped on the server https://github.com/Kinto/kinto-attachment/pull/724
> Drop gzipped option when uploading attachments
